#!/bin/bash

python3 -m venv venv
echo "Created virtual environment.."
source ./venv/bin/activate
pip install -r requirements.txt
pyinstaller --onefile TimetableExcelParser.py
echo "Successfully build ./dist/TimetableExcelParser"
